apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rey
  labels:
    run: rey
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: rey
    spec:
      containers:
      - name: rey
        image: luizalabs/rey:v0.3.0
        volumeMounts:
        - mountPath: /etc/rey
          name: rey-components
      volumes:
      - name: rey-components
        configMap:
          name: rey-components
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: rey
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: rey
  type: ClusterIP
